//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrestComplaintWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Ticket1 = new HashSet<Ticket>();
        }
    
        public int TicketId { get; set; }
        public string TicketOrigin { get; set; }
        public Nullable<int> ParentTicketId { get; set; }
        public string TicketNumber { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> TicketPriorityId { get; set; }
        public string Label { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ActualCloseDate { get; set; }
        public Nullable<int> ReportedBy { get; set; }
        public int TicketTypeId { get; set; }
        public Nullable<int> PropertyDetaildId { get; set; }
        public int StatusTypeId { get; set; }
        public Nullable<System.DateTime> ExpectedCloseDate { get; set; }
        public Nullable<int> PropertyId { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<int> LastupdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsPaused { get; set; }
        public Nullable<int> PausedBy { get; set; }
        public Nullable<System.DateTime> PausedDate { get; set; }
        public Nullable<System.DateTime> PausedTilDate { get; set; }
        public string PausedComment { get; set; }
        public Nullable<bool> IsReopen { get; set; }
        public Nullable<System.DateTime> ReOpenOn { get; set; }
        public Nullable<int> ReopenBy { get; set; }
        public string ReopenReason { get; set; }
        public string TicketChannel { get; set; }
        public string Visibility { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket1 { get; set; }
        public virtual Ticket Ticket2 { get; set; }
    }
}
